routes/web.php
<?php
// use Symfony\Component\Routing\Route;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'AdminController@getIndex')->name('home');


Route::group(['middleware' => ['auth']], function () {
    Route::group(['prefix' => 'admin'], function () {


        Route::get('/approval', 'AdminController@approval')->name('approval');

        Route::middleware(['admin'])->group(function () {
            Route::get('/users', 'UserController@index')->name('admin.users.index');
            Route::get('/users/{user_id}/approve', 'UserController@approve')->name('admin.users.approve');
        });

        Route::middleware(['approved'])->group(function () {
            Route::get('', 'AdminController@getIndex')->name('admin');      
            Route::get('/change-password', 'AdminController@getchangePassword')->name('getChangePassword'); 
            Route::post('/changePassword','AdminController@changePassword')->name('changePassword');
            
            Route::resource('category', 'CategoryController');
            Route::resource('product', 'ProductController');
            Route::resource('cart', 'CartController');
            Route::resource('slide', 'SlideController');

            Route::get('orders', 'OrderController@index')->name('order.index');
            Route::get('order/{id}', 'OrderController@getDetail')->name('order.detail');
        });
    });
});

Route::get('', 'PageController@getIndex')->name('trang-chu');
Route::get('cua-hang/{id}', 'PageController@getShop')->name('cua-hang');
Route::get('san-pham/{id}', 'PageController@getProduct')->name('san-pham');
Route::get('gio-hang', 'PageController@getCart')->name('gio-hang');

Route::get('thanh-toan', 'PageController@getCheckout')->name('thanh-toan');
Route::post('thanh-toan', 'CartController@postComplete')->name('complete');

Route::get('gioi-thieu', 'PageController@getAbout')->name('gioi-thieu');

Route::get('lien-he', 'PageController@getContact')->name('lien-he');
Route::post('lien-he', 'PageController@postContact')->name('contact.post');

Route::get('complete', 'PageController@getComplete')->name('complete');


Route::group(['prefix' => 'cart'], function () {
    Route::get('add/{id}', 'CartController@getAddCart')->name('addcart');
    Route::get('remove/{id}', 'CartController@getRemoveCart')->name('removecart');
    Route::get('update', 'CartController@getUpdateCart')->name('updatecart');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name','slug'
    ];
    public function products()
    {
        return $this->hasMany('App\Product','category_id','id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;

class CategoryController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::withCount('products')->get();
        return view('admin.category.index', compact('categories'));      
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryRequest $request)
    {
        $category = new Category;
        $category->name = $request->name;
        $category->slug = str_slug($request->name);
        $category->save();
        return back()->with('thongbao','Thêm thành công!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cat = Category::find($id); 
        return view('admin.category.edit', compact('cat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request,$id)
    {
        $cat = Category::find($id); 
        $cat->name = request('name');    
        $cat->save();

        return back()->with('thongbao','Sửa thành công!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cate = Category::where('id',$id)->withCount('products')->first();
        if($cate->products_count){
            return back()->withErrors('Mục này đã có sản phẩm. Không thể xóa!');
        }
        else {
            Category::destroy($id);
            return back()->with('thongbao','Xóa thành công!');
        }
    }
}

resources/views/admin/category/edit.blade.php
@extends('layouts.admin.master')

@section('title','Category')

@section('content')
@include('layouts.admin.sidebar')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-4">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="page-header">Danh mục sản phẩm</h1>
                @include('thongbao')
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-3">
                <div class="card">
                    <div class="card-header">
                        Sửa danh mục: {{$cat->name}}
                    </div>
                    <div class="card-body">

                        <form action="{{route('category.update',$cat->id) }}" method="post">
                            @method('PATCH')
                            @csrf
                            <div class="form-group">
                                <label>Tên danh mục:</label>
                                <input type="text" name="name" class="form-control" placeholder="Tên danh mục..." required value="{{$cat['name']}}">
                            </div>
                            @include('error.note')
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary my-3 px-4">Lưu</button>                       
                                <button type="reset" class="btn btn-danger my-3 px-4">Hủy bỏ</button>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>
        <!--/.row-->
    </div>
</main>
@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.admin.master')

@section('title','Category')

@section('content')
@include('layouts.admin.sidebar')
<div role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-4">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="page-header">Danh mục sản phẩm</h1>
        @include('error.note')
        @include('thongbao')
      </div>
    
      <div class="col-12 mb-3">
        <div class="card">
          <div class="card-header">
            <a class="" data-toggle="collapse" href="#createCategory" role="button" aria-expanded="false" aria-controls="createCategory">
              Thêm danh mục
            </a>
          </div>
          <div class="collapse" id="createCategory">
            <div class="card-body">

              <form action="" method="post">
                @csrf                
                <div class="form-group">
                  <label>Tên danh mục:</label>
                  <input type="text" name="name" class="form-control" placeholder="Tên danh mục..." required>
                </div>
                <button type="submit" class="btn btn-primary my-3 px-4">Thêm</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 mb-3">
        <div class="card">
          <div class="card-header">
            <a class="" data-toggle="collapse" href="#categoryList" role="button" aria-expanded="false" aria-controls="categoryList">
              Danh sách danh mục
            </a>
          </div>
          <div class="collapse show" id="categoryList">
            <div class="card-body" class="table-responsive">
              <table class="table table-bordered" id="myTable">
                <thead class="thead-primary">
                  <tr class="text-center">
                    <th>Tên danh mục</th>
                    <th>Số lượng sản phẩm</th>
                    <th style="width:30%">Tùy chọn</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($categories as $item)
                  <tr>
                    <td>{{$item->name}}</td>
                    <td align="center">{{$item->products_count}}</td>
                    <td align="center">
                      <form method="POST" action="{{route('category.destroy',$item->id) }}">
                        @csrf
                        @method('DELETE')
                        <div class="field">
                          <div class="control">
                            <a href="{{route('category.edit',$item->id)}}" class="btn btn-warning my-1"><span class="glyphicon glyphicon-edit"></span> Sửa</a>
                            <button type="submit" onclick="return confirm('Bạn có chắc chắn muốn xóa?')" class="btn btn-danger my-1"><span class="glyphicon glyphicon-trash"></span> Xóa</button>
                          </div>
                        </div>
                      </form>
                    </td>
                  </tr>
                  @endforeach


                </tbody>
              </table>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
      </div>
    <!--/.row-->
  </div>
</div>
@endsection

@section('script')
<script>
  $(document).ready(function() {
    $('#myTable').DataTable();
  });
</script>
@endsection