routes/web.php
<?php
// use Symfony\Component\Routing\Route;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'AdminController@getIndex')->name('home');


Route::group(['middleware' => ['auth']], function () {
    Route::group(['prefix' => 'admin'], function () {


        Route::get('/approval', 'AdminController@approval')->name('approval');

        Route::middleware(['admin'])->group(function () {
            Route::get('/users', 'UserController@index')->name('admin.users.index');
            Route::get('/users/{user_id}/approve', 'UserController@approve')->name('admin.users.approve');
        });

        Route::middleware(['approved'])->group(function () {
            Route::get('', 'AdminController@getIndex')->name('admin');      
            Route::get('/change-password', 'AdminController@getchangePassword')->name('getChangePassword'); 
            Route::post('/changePassword','AdminController@changePassword')->name('changePassword');
            
            Route::resource('category', 'CategoryController');
            Route::resource('product', 'ProductController');
            Route::resource('cart', 'CartController');
            Route::resource('slide', 'SlideController');

            Route::get('orders', 'OrderController@index')->name('order.index');
            Route::get('order/{id}', 'OrderController@getDetail')->name('order.detail');
        });
    });
});

Route::get('', 'PageController@getIndex')->name('trang-chu');
Route::get('cua-hang/{id}', 'PageController@getShop')->name('cua-hang');
Route::get('san-pham/{id}', 'PageController@getProduct')->name('san-pham');
Route::get('gio-hang', 'PageController@getCart')->name('gio-hang');

Route::get('thanh-toan', 'PageController@getCheckout')->name('thanh-toan');
Route::post('thanh-toan', 'CartController@postComplete')->name('complete');

Route::get('gioi-thieu', 'PageController@getAbout')->name('gioi-thieu');

Route::get('lien-he', 'PageController@getContact')->name('lien-he');
Route::post('lien-he', 'PageController@postContact')->name('contact.post');

Route::get('complete', 'PageController@getComplete')->name('complete');


Route::group(['prefix' => 'cart'], function () {
    Route::get('add/{id}', 'CartController@getAddCart')->name('addcart');
    Route::get('remove/{id}', 'CartController@getRemoveCart')->name('removecart');
    Route::get('update', 'CartController@getUpdateCart')->name('updatecart');
});

app/Slide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{
    protected $table = 'slides';

    protected $fillable = [
        'pic'
    ];
}

app/Http/Controllers/SlideController.php
<?php

namespace App\Http\Controllers;

use App\Slide;
use Illuminate\Http\Request;
use App\Http\Requests\StoreSlideRequest;
use App\Http\Requests\UpdateSlideRequest;

class SlideController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slides = Slide::all();
        return view('admin.slide.index',compact('slides'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.slide.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSlideRequest $request)
    {
        $fileName = time()."_".$request->pic->getClientOriginalName();

        $slide = new Slide();
        $slide->pic = $fileName;
        $slide->title = $request->title;
        $slide->desc = $request->desc;
        $slide->save();
        $request->pic->move('uploads',$fileName);
        return back()->with('thongbao','Thêm thành công!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function show(Slide $slide)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $slide = Slide::find($id);
        return view('admin.slide.edit',compact('slide'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSlideRequest $request, $id)
    {
        $slide = Slide::find($id);
        $slide->title = $request->title;
        $slide->desc = $request->desc;
        if($request->hasFile('pic')){
            $fileName = time()."_".$request->pic->getClientOriginalName();         
            $request->pic->move('uploads',$fileName);
            unlink("uploads/".$slide->pic);
            $slide->pic = $fileName;
        }
        $slide->save();
        return back()->with('thongbao','Sửa thành công!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Slide::destroy($id);
        return back()->with('thongbao','Xóa thành công!');
    }
}

resources/views/admin/slide/create.blade.php
@extends('layouts.admin.master')

@section('title','Slide')

@section('content')
@include('layouts.admin.sidebar')
<div role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-4">
    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Slide</h1>
            @include('thongbao')
        </div>
    </div><!--/.row-->
    
    <div class="row">
        <div class="col-xs-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">Thêm Slide</div>
                <div class="card-body">
                    
                    <form method="post" class="container mt-4" action="{{route('slide.store') }}" enctype="multipart/form-data">
                        @csrf
                        @include('error.note')
                        <div class="row" style="margin-bottom:40px">
                            <div class="col">                                                              
                                <div class="form-group" >
                                    <label>Hình ảnh</label>
                                    <input required id="pic" type="file" name="pic" class="form-control hidden" onchange="changeImg(this)">                                                                  
                                </div>   
                                <div class="form-group" >
                                    <label>Tiêu đề</label>
                                    <input required type="text" name="title" class="form-control">
                                </div>
                                <div class="form-group" >
                                    <label>Miêu tả</label>
                                    <textarea  name="desc" class="d-block" style="width:100%"></textarea>
                                </div>                                     
                               
                                <input type="submit" name="submit" value="Thêm" class="btn btn-primary">
                                <a href="{{route('slide.index')}}" class="btn btn-danger">Hủy bỏ</a>
                            </div>
                        </div>
                    </form>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div><!--/.row-->
</div>
</div>	<!--/.main-->
@endsection

@section('script')
@endsection

resources/views/admin/slide/edit.blade.php
@extends('layouts.admin.master')

@section('title','Slide')

@section('content')
@include('layouts.admin.sidebar')
<div role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-4">
    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Slide</h1>
            @include('thongbao')
        </div>
    </div><!--/.row-->
    
    <div class="row">
        <div class="col-xs-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">Sửa Slide</div>
                <div class="card-body">
                    
                    <form method="post" class="container mt-4" action="{{route('slide.update',$slide->id) }}" enctype="multipart/form-data">
                        @method('PATCH')
                        @csrf
                        @include('error.note')
                        <div class="row" style="margin-bottom:40px">
                            <div class="col">                                                              
                                <div class="form-group" >
                                    <label>Hình ảnh</label>
                                    <img src="uploads/{{$slide->pic}}"  height="300px" alt="" class="d-block">
                                    <input  id="pic" type="file" name="pic" class="form-control hidden" onchange="changeImg(this)">                                                                  
                                </div>   
                                <div class="form-group" >
                                    <label>Tiêu đề</label>
                                    <input required type="text" name="title" class="form-control" value="{{$slide->title}}">
                                </div>
                                <div class="form-group" >
                                    <label>Miêu tả</label>
                                    <textarea  name="desc" class="d-block" style="width:100%">{{$slide->desc}}</textarea>
                                </div>                                     
                               
                                <input type="submit" name="submit" value="Sửa" class="btn btn-primary">                        
                                <a href="{{route('slide.index')}}" class="btn btn-danger">Hủy bỏ</a>
                            </div>
                        </div>
                    </form>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div><!--/.row-->
</div>
</div>	<!--/.main-->
@endsection

@section('script')
@endsection

resources/views/admin/slide/index.blade.php
@extends('layouts.admin.master')

@section('title','Slide')

@section('content')
@include('layouts.admin.sidebar')
<div role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-4">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="page-header">Slide</h1>
        @include('thongbao')       
        @include('error.note')
      </div>
    </div>
    <!--/.row-->

    <div class="row">
      <div class="col-12 mb-3">
        <div class="card">
          <div class="card-header">
            <a class="" data-toggle="collapse" href="#createSlide" role="button" aria-expanded="false" aria-controls="createSlide">
              Thêm Slide
            </a>
          </div>
          <div class="collapse" id="createSlide">
            <div class="card-body">
              <form method="post" class="container mt-4" action="{{route('slide.store') }}" enctype="multipart/form-data">
                @csrf
                @include('error.note')
                <div class="row" style="margin-bottom:40px">
                  <div class="col">
                    <div class="form-group">
                      <label>Hình ảnh</label>
                      <input required id="pic" type="file" name="pic" class="form-control hidden" onchange="changeImg(this)">
                    </div>
                    <div class="form-group">
                      <label>Tiêu đề</label>
                      <input required type="text" name="title" class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Miêu tả</label>
                      <textarea name="desc" class="d-block" style="width:100%"></textarea>
                    </div>

                    <input type="submit" name="submit" value="Thêm" class="btn btn-primary">
                    <a href="{{route('slide.index')}}" class="btn btn-danger">Hủy bỏ</a>
                  </div>
                </div>
              </form>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 mb-3">
        <!-- <div class="my-3">
          <a href="{{route('slide.create')}}" class="btn btn-primary">Thêm slide</a>
        </div> -->
        <div class="card">
          <div class="card-header">
            <a class="" data-toggle="collapse" href="#slideList" role="button" aria-expanded="false" aria-controls="slideList">
              Danh sách Slide
            </a>
          </div>
          <div class="collapse show" id="slideList">
            <div class="card-body">
              <div class="bootstrap-table">
                <div class="table-responsive">
                  <table class="table table-bordered " id="myTable">
                    <thead>
                      <tr class="">
                        <th>ID</th>
                        <th>Ảnh</th>
                        <th>Tiêu đề</th>
                        <th>Mô tả</th>
                        <th>Tùy chọn</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($slides as $item)
                      <tr>
                        <td>{{$item->id}}</td>
                        <td>
                          <img width="200px" src="uploads/{{$item->pic}}" class="thumbnail">
                        </td>
                        <td>{{$item->title}}</td>
                        <td>{{$item->desc}}</td>
                        <td>
                          <form method="POST" action="{{route('slide.destroy',$item->id) }}">
                            @csrf
                            @method('DELETE')
                            <div class="field">
                              <div class="control">
                                <a href="{{route('slide.edit',$item->id)}}" class="btn btn-warning my-1"><span class="glyphicon glyphicon-edit"></span> Sửa</a>
                                <button type="submit" onclick="return confirm('Bạn có chắc chắn muốn xóa?')" class="btn btn-danger  my-1"><span class="glyphicon glyphicon-trash"></span> Xóa</button>
                              </div>
                            </div>
                          </form>
                        </td>
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/.row-->
  </div>
</div>
<!--/.main-->
@endsection
@section('script')
<script>
  $(document).ready(function() {
    $('#myTable').DataTable();
  });
</script>
@endsection