routes/web.php
<?php
// use Symfony\Component\Routing\Route;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'AdminController@getIndex')->name('home');


Route::group(['middleware' => ['auth']], function () {
    Route::group(['prefix' => 'admin'], function () {


        Route::get('/approval', 'AdminController@approval')->name('approval');

        Route::middleware(['admin'])->group(function () {
            Route::get('/users', 'UserController@index')->name('admin.users.index');
            Route::get('/users/{user_id}/approve', 'UserController@approve')->name('admin.users.approve');
        });

        Route::middleware(['approved'])->group(function () {
            Route::get('', 'AdminController@getIndex')->name('admin');      
            Route::get('/change-password', 'AdminController@getchangePassword')->name('getChangePassword'); 
            Route::post('/changePassword','AdminController@changePassword')->name('changePassword');
            
            Route::resource('category', 'CategoryController');
            Route::resource('product', 'ProductController');
            Route::resource('cart', 'CartController');
            Route::resource('slide', 'SlideController');

            Route::get('orders', 'OrderController@index')->name('order.index');
            Route::get('order/{id}', 'OrderController@getDetail')->name('order.detail');
        });
    });
});

Route::get('', 'PageController@getIndex')->name('trang-chu');
Route::get('cua-hang/{id}', 'PageController@getShop')->name('cua-hang');
Route::get('san-pham/{id}', 'PageController@getProduct')->name('san-pham');
Route::get('gio-hang', 'PageController@getCart')->name('gio-hang');

Route::get('thanh-toan', 'PageController@getCheckout')->name('thanh-toan');
Route::post('thanh-toan', 'CartController@postComplete')->name('complete');

Route::get('gioi-thieu', 'PageController@getAbout')->name('gioi-thieu');

Route::get('lien-he', 'PageController@getContact')->name('lien-he');
Route::post('lien-he', 'PageController@postContact')->name('contact.post');

Route::get('complete', 'PageController@getComplete')->name('complete');


Route::group(['prefix' => 'cart'], function () {
    Route::get('add/{id}', 'CartController@getAddCart')->name('addcart');
    Route::get('remove/{id}', 'CartController@getRemoveCart')->name('removecart');
    Route::get('update', 'CartController@getUpdateCart')->name('updatecart');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name','slug','pic','desc','price','category_id',
    ];

    public function category(){
        return $this->belongsTo('App\Category','category_id','id');
    }
    
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $categories = Category::all();
        return view('admin.product.index', compact('products','categories'));  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.product.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {      
        
        $fileName = time()."_".$request->pic->getClientOriginalName();       

        $product = new Product();
        $product->category_id = $request->cate;
        $product->name = $request->name;
        $product->slug = str_slug($request->name);
        $product->pic = $fileName;
        $product->spec = $request->spec;
        $product->desc = $request->desc;
        $product->short_desc = $request->short_desc;
        $product->price = $request->price;             
        $product->save();
        $request->pic->move('uploads',$fileName);

        return back()->with('thongbao','Thêm thành công!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show( $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id); 
        $categories = Category::all();
        return view('admin.product.edit', compact('product','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, $id)
    {
        $product =  Product::find($id);
        $product->category_id = $request->cate;
        $product->name = $request->name;
        $product->slug = str_slug($request->name);        
        $product->spec = $request->spec;
        $product->desc = $request->desc;
        $product->short_desc = $request->short_desc;
        $product->price = $request->price;             


        if($request->hasFile('pic')){
            $fileName = time()."_".$request->pic->getClientOriginalName();         
            $request->pic->move('uploads',$fileName);
            unlink("uploads/".$product->pic);
            $product->pic = $fileName;
        }

        $product->save();        

        return back()->with('thongbao','Sửa thành công!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);
        return back()->with('thongbao','Xóa thành công!');
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.admin.master')

@section('title','Product')

@section('content')
@include('layouts.admin.sidebar')
<div role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-4">
    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Sản phẩm</h1>
            @include('thongbao')
        </div>
    </div><!--/.row-->
    
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">Thêm sản phẩm</div>
                <div class="card-body">
                    
                    <form method="post" class="container mt-4" action="{{route('product.store') }}" enctype="multipart/form-data">
                        @csrf
                        @include('error.note')
                        <div class="row" style="margin-bottom:40px">
                            <div class="col">
                                <div class="form-group" >
                                    <label>Tên sản phẩm</label>
                                    <input required type="text" name="name" class="form-control">
                                </div>
                                <div class="form-group" >
                                    <label>Giá sản phẩm</label>
                                    <input required type="number" name="price" class="form-control">
                                </div>
                                <div class="form-group" >
                                    <label>Ảnh sản phẩm</label>
                                    <input required id="pic" type="file" name="pic" class="form-control hidden" onchange="changeImg(this)">                                                                  
                                </div>   
                                <div class="form-group" >
                                        <label>Miêu tả</label>
                                        <textarea  name="short_desc" class="d-block" style="width:100%"></textarea>
                                    </div>             
                                <div class="form-group" >
                                    <label>Miêu tả chi tiết</label>
                                    <textarea name="desc" id="desc" ></textarea>                                
                                </div>
                                <div class="form-group" >
                                    <label>Thông tin bổ sung</label>
                                    <textarea name="spec" id="spec" ></textarea>    
                                </div>
                            
                                <div class="form-group" >
                                    <label>Danh mục</label>
                                    <select required name="cate" class="form-control">
                                        @foreach ($categories as $item)
                                            <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach                                     
                                    </select>
                                </div>
                                <input type="submit" name="submit" value="Thêm" class="btn btn-primary">
                                <a href="{{route('product.index')}}" class="btn btn-danger">Hủy bỏ</a>
                            </div>
                        </div>
                    </form>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div><!--/.row-->
</div>
</div>	<!--/.main-->
@endsection

@section('script')
<script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'desc',{
        language: 'vi',
        filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
	    filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
    } );
    CKEDITOR.replace( 'spec',{
        language: 'vi',
        filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
	    filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
    } );
</script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.admin.master')

@section('title','Product')

@section('content')
@include('layouts.admin.sidebar')
<div role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-4">
    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Sản phẩm</h1>
            @include('thongbao')
        </div>
    </div><!--/.row-->
    
    <div class="row">
        <div class="col-xs-12 col-md-12 col-lg-12">              
            <div class="card">
                <div class="card-header">Sửa sản phẩm: <strong>{{$product->name}}</strong> </div>
                <div class="card-body">
                    
                    <form method="post" class="container mt-4" action="{{route('product.update',$product->id) }}" enctype="multipart/form-data">
                        @method('PATCH')
                        @csrf
                        @include('error.note')
                        <div class="row" style="margin-bottom:40px">
                            <div class="col">
                                <div class="form-group" >
                                    <label>Tên sản phẩm</label>
                                    <input required type="text" name="name" class="form-control" value="{{$product->name}}">
                                </div>
                                <div class="form-group" >
                                    <label>Giá sản phẩm</label>
                                    <input required type="number" name="price" class="form-control" value="{{$product->price}}">
                                </div>
                                <div class="form-group" >
                                    <label>Ảnh sản phẩm</label>                                                                        
                                    <p class="mb-2"><img id="avatar" class="thumbnail" width="300px" src="uploads/{{$product->pic}}"></p>
                                    <input  id="pic" type="file" name="pic" class="form-control hidden" onchange="changeImg(this)" >
                                </div>   
                                <div class="form-group" >
                                        <label>Miêu tả</label>
                                    <textarea  name="short_desc" class="d-block" style="width:100%">{{$product->short_desc}}</textarea>
                                    </div>             
                                <div class="form-group" >
                                    <label>Miêu tả chi tiết</label>
                                    <textarea name="desc" id="desc" >{{$product->desc}}</textarea>                                
                                </div>
                                <div class="form-group" >
                                    <label>Thông tin bổ sung</label>
                                    <textarea name="spec" id="spec" >{{$product->spec}}</textarea>    
                                </div>
                            
                                <div class="form-group" >
                                    <label>Danh mục</label>
                                    <select required name="cate" class="form-control">
                                        @foreach ($categories as $item)
                                            <option 
                                            @if ($product->category_id == $item->id)
                                                {{ "selected" }}
                                            @endif
                                            value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach                                     
                                    </select>
                                </div>
                                <button type="submit" name="submit"  class="btn btn-primary">Lưu</button>                                
                                <a href="{{route('product.index')}}" class="btn btn-danger">Hủy bỏ</a>
                            </div>
                        </div>
                    </form>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div><!--/.row-->
</div>
</div>	<!--/.main-->
@endsection

@section('script')
<script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'desc',{
        language: 'vi',
        filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
	    filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
    } );
    CKEDITOR.replace( 'spec',{
        language: 'vi',
        filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
	    filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
    } );
</script>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.admin.master')

@section('title','Product')

@section('content')
@include('layouts.admin.sidebar')
<div role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Sản phẩm</h1>
                @include('thongbao')
            </div>
        </div>
        <!--/.row-->
        <div class="row">
            <div class="col-12 mb-3">
                <div class="card">
                    <div class="card-header">
                        <a class="" data-toggle="collapse" href="#createProduct" role="button" aria-expanded="false" aria-controls="createProduct">
                            Thêm sản phẩm
                        </a>
                    </div>
                    <div class="collapse" id="createProduct">
                        <div class="card-body">
                            <form method="post" class="container mt-4" action="{{route('product.store') }}" enctype="multipart/form-data">
                                @csrf
                                @include('error.note')
                                <div class="row" style="margin-bottom:40px">
                                    <div class="col">
                                        <div class="form-group">
                                            <label>Tên sản phẩm</label>
                                            <input required type="text" name="name" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label>Giá sản phẩm</label>
                                            <input required type="number" name="price" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label>Ảnh sản phẩm</label>
                                            <input required id="pic" type="file" name="pic" class="form-control hidden" onchange="changeImg(this)">
                                        </div>
                                        <div class="form-group">
                                            <label>Miêu tả</label>
                                            <textarea name="short_desc" class="d-block" style="width:100%"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Miêu tả chi tiết</label>
                                            <textarea name="desc" id="desc"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Thông tin bổ sung</label>
                                            <textarea name="spec" id="spec"></textarea>
                                        </div>

                                        <div class="form-group">
                                            <label>Danh mục</label>
                                            <select required name="cate" class="form-control">
                                                @foreach ($categories as $item)
                                                <option value="{{$item->id}}">{{$item->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <button type="submit" name="submit"  class="btn btn-primary">Thêm</button>
                                        <!-- <a href="{{route('product.index')}}" class="btn btn-danger">Hủy bỏ</a> -->
                                    </div>
                                </div>
                            </form>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 mb-3">
                <!-- <div class="my-3">
                    <a href="{{route('product.create')}}" class="btn btn-primary">Thêm sản phẩm</a>
                </div> -->
                <div class="card">
                    <div class="card-header">
                        <a class="" data-toggle="collapse" href="#productList" role="button" aria-expanded="false" aria-controls="productList">
                            Danh sách sản phẩm
                        </a>
                    </div>
                    <div class="collapse show" id="productList">
                        <div class="card-body">
                            <div class="bootstrap-table">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="myTable">
                                        <thead>
                                            <tr class="">
                                                <th>ID</th>
                                                <th>Tên Sản phẩm</th>
                                                <th>Giá sản phẩm</th>
                                                <th>Ảnh sản phẩm</th>
                                                <th>Danh mục</th>
                                                <th>Tùy chọn</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($products as $item)
                                            <tr>
                                                <td>{{$item->id}}</td>
                                                <td>{{$item->name}}</td>
                                                <td>{{number_format($item->price, 0, '', '.') . ' đ'}}</td>
                                                <td>
                                                    <img width="200px" src="uploads/{{$item->pic}}" class="thumbnail">
                                                </td>
                                                <td>{{$item->category->name}}</td>
                                                <td>
                                                    <form method="POST" action="{{route('product.destroy',$item->id) }}">
                                                        @csrf
                                                        @method('DELETE')
                                                        <div class="field">
                                                            <div class="control">
                                                                <a href="{{route('product.edit',$item->id)}}" class="btn btn-warning my-1"><span class="glyphicon glyphicon-edit"></span> Sửa</a>
                                                                <button type="submit" onclick="return confirm('Bạn có chắc chắn muốn xóa?')" class="btn btn-danger my-1"><span class="glyphicon glyphicon-trash"></span> Xóa</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!--/.row-->
    </div>
</div>
<!--/.main-->
@endsection
@section('script')
<script>
    $(document).ready(function() {
        $('#myTable').DataTable();
    });
</script>
<script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('desc', {
        language: 'vi',
        filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
        filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
    });
    CKEDITOR.replace('spec', {
        language: 'vi',
        filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
        filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
    });
</script>
@endsection