routes/web.php
<?php
// use Symfony\Component\Routing\Route;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'AdminController@getIndex')->name('home');


Route::group(['middleware' => ['auth']], function () {
    Route::group(['prefix' => 'admin'], function () {


        Route::get('/approval', 'AdminController@approval')->name('approval');

        Route::middleware(['admin'])->group(function () {
            Route::get('/users', 'UserController@index')->name('admin.users.index');
            Route::get('/users/{user_id}/approve', 'UserController@approve')->name('admin.users.approve');
        });

        Route::middleware(['approved'])->group(function () {
            Route::get('', 'AdminController@getIndex')->name('admin');      
            Route::get('/change-password', 'AdminController@getchangePassword')->name('getChangePassword'); 
            Route::post('/changePassword','AdminController@changePassword')->name('changePassword');
            
            Route::resource('category', 'CategoryController');
            Route::resource('product', 'ProductController');
            Route::resource('cart', 'CartController');
            Route::resource('slide', 'SlideController');

            Route::get('orders', 'OrderController@index')->name('order.index');
            Route::get('order/{id}', 'OrderController@getDetail')->name('order.detail');
        });
    });
});

Route::get('', 'PageController@getIndex')->name('trang-chu');
Route::get('cua-hang/{id}', 'PageController@getShop')->name('cua-hang');
Route::get('san-pham/{id}', 'PageController@getProduct')->name('san-pham');
Route::get('gio-hang', 'PageController@getCart')->name('gio-hang');

Route::get('thanh-toan', 'PageController@getCheckout')->name('thanh-toan');
Route::post('thanh-toan', 'CartController@postComplete')->name('complete');

Route::get('gioi-thieu', 'PageController@getAbout')->name('gioi-thieu');

Route::get('lien-he', 'PageController@getContact')->name('lien-he');
Route::post('lien-he', 'PageController@postContact')->name('contact.post');

Route::get('complete', 'PageController@getComplete')->name('complete');


Route::group(['prefix' => 'cart'], function () {
    Route::get('add/{id}', 'CartController@getAddCart')->name('addcart');
    Route::get('remove/{id}', 'CartController@getRemoveCart')->name('removecart');
    Route::get('update', 'CartController@getUpdateCart')->name('updatecart');
});

resources/views/layouts/admin/header.blade.php
<nav class="navbar navbar-expand-md no-gutters navbar-light bg-white shadow-sm fixed-top">
    <div class="col-2 text-left">
        <a href="">
            <img src="images/logo.png" height="30" alt="image">
        </a>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav justify-content-end ml-md-auto">
            <!-- Authentication Links -->
            @guest
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ __('Đăng nhập') }}</a>
            </li>
            @if (Route::has('register'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">{{ __('Đăng ký') }}</a>
            </li>
            @endif
            @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('getChangePassword') }}">Đổi mật khẩu</a>
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        {{ __('Đăng xuất') }}
                    </a>
                   
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
            @endguest
        </ul>
    </div>
</nav>

resources/views/layouts/admin/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ config('app.name', 'Laravel') }} - @yield('title')</title>
    <base href="{{asset('')}}">

    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="source/css/bootstrap.min.css">
    {{-- <link rel="stylesheet" href="source/css/ionicons.min.css"> --}}
    <link rel="stylesheet" type="text/css" href="source/css/datatables.min.css"/>
    <link rel="stylesheet" href="css/style.css">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <!-- <link href="dashboard.css" rel="stylesheet"> -->
</head>

<body>

    @include('layouts.admin.header')

    <div class="container-fluid" style="align-items: stretch">
        <div class="row pt-5">     
             @yield('content')
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- <script>
        window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')
    </script>
    <script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script> -->

	<script src="source/js/popper.min.js"></script>
    <script src="source/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="source/js/datatables.min.js"></script>
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
    @yield('script')
</body>

</html>

resources/views/layouts/admin/sidebar.blade.php
<style>
    .nav-link{
        color: #ffffff;
    }
    .nav-link:hover{
        color: #ecf0f1;
    }
    ul.nav li.divider {
        border-bottom: 1px solid #eee;
        margin: .5rem 0;
    }
</style>
<nav class="col-md-2 d-none d-md-block bg-primary pt-4 position-fixed h-100" id="sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="{{route('admin')}}">
                    <span class="icon ion-md-home"></span>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            <li role="presentation" class="divider"></li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('category.index')}}">
                    <span class="icon ion-md-folder"></span>
                    Danh mục
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('product.index')}}">
                    <span class="icon ion-md-cube"></span>
                    Sản phẩm
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('slide.index')}}">
                    <span class="icon ion-md-images"></span>
                    Slide
                </a>
            </li>       
            <li role="presentation" class="divider"></li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('order.index')}}">
                    <span class="icon ion-md-barcode"></span>
                    Đơn hàng
                </a>
            </li>       
            @if (Auth::user()->admin)
            <li role="presentation" class="divider"></li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('admin.users.index')}}">
                    <span class="icon ion-md-person"></span>
                    Phê duyệt tài khoản
                </a>
            </li>
            @endif
            
        </ul>
    </div>
</nav>